### ISSUE TITLE
7.0.18 listObjects broken

### ISSUE THREAD

**Issue by PacoDu** [minio/minio-js#886]
Since 7.0.18 we are experiencing errors with minio client and listObjects. I think the issue was introduced by https://github.com/minio/minio-js/pull/877. Also I think there is an issue in the way #877 was merged because xml2js dependency is reintroduced which reverts part of https://github.com/minio/minio-js/pull/861

```js
// ...
const res = await minioClient.listObjects(bucket, objectKey, true)
```

```
TypeError: xmlobj.Contents.forEach is not a function
    at parseListObjects (/app/node_modules/minio/dist/main/xml-parsers.js:387:21)
    at DestroyableTransform._flush (/app/node_modules/minio/dist/main/transformers.js:88:19)
    at DestroyableTransform.prefinish (/app/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:314:20)
    at prefinish (/app/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/app/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/app/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/app/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (_stream_readable.js:683:10)
    at Object.onceWrapper (events.js:420:28)
```

**Comment by ebozduman** [comment]
@PacoDu 

Yes. This is a regression due to #877. PR#887 fixes it.

> issue in the way #877 was merged because `xml2js` dependency is reintroduced

We still use the faster xml parser, `fxp`, for parsing and get the benefit of its speed.
We had to bring back `xml2js` module, because we also need another functionality of it, conversion from json to xml, which does not come with `fxp` module.

**Comment by PacoDu** [comment]
@ebozduman Oh ok i see, thanks for explanation and the quick fix 🚀  !

**Comment by starpit** [comment]
Is there a plan to release this fix in a 7.0.19?

**Comment by fschuetz04** [comment]
Any update on this? The latest version is still 7.0.18, which does not include the mentioned fix.

**Comment by prakashsvmx** [comment]
@fschuetz04 we are planning for a release soon. Please stay tuned.

**Comment by gmacmaster** [comment]
Any ideas as to what soon will be?

**Comment by prakashsvmx** [comment]
@kannappanr
